/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask */
        post: operations["ask_api_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ask/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask Stream */
        post: operations["ask_stream_api_ask_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluations/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Evaluation */
        get: operations["latest_evaluation_api_evaluations_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metadata */
        get: operations["metadata_api_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Policy Catalog */
        get: operations["policy_catalog_api_policies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policies/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Policy Detail */
        get: operations["policy_detail_api_policies__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AskRequest */
        AskRequest: {
            /** Question */
            question: string;
        };
        /** AskResponse */
        AskResponse: {
            /** Answer */
            answer: string;
            /** Backend */
            backend: string;
            /** Citations */
            citations: components["schemas"]["Citation"][];
            /** Completion Tokens */
            completion_tokens?: number | null;
            /** Finish Reason */
            finish_reason?: string | null;
            /**
             * Latency Ms
             * @default 0
             */
            latency_ms: number;
            /** Model */
            model?: string | null;
            /** Prompt Tokens */
            prompt_tokens?: number | null;
            /** Refused */
            refused: boolean;
            /** Request Id */
            request_id?: string;
        };
        /** Citation */
        Citation: {
            /** Document Id */
            document_id: string;
            /** Score */
            score: number;
            /** Source */
            source: string;
            /** Title */
            title: string;
        };
        /** EvaluationCase */
        EvaluationCase: {
            /** Answer */
            answer: string;
            /** Case */
            case: number;
            /** Expected Answerable */
            expected_answerable: boolean;
            /** Expected Document Id */
            expected_document_id: string | null;
            /** Keyword Coverage */
            keyword_coverage: number;
            /** Observed Citation Ids */
            observed_citation_ids: string[];
            /** Observed Refused */
            observed_refused: boolean;
            /** Passed */
            passed: boolean;
            /** Question */
            question: string;
            /** Refusal Correct */
            refusal_correct: boolean;
            /** Retrieval Correct */
            retrieval_correct: boolean;
        };
        /** EvaluationMetrics */
        EvaluationMetrics: {
            /** Examples */
            examples: number;
            /** Keyword Coverage */
            keyword_coverage: number;
            /** Refusal Accuracy */
            refusal_accuracy: number;
            /** Retrieval Accuracy */
            retrieval_accuracy: number;
        };
        /** EvaluationReport */
        EvaluationReport: {
            /** Cases */
            cases: components["schemas"]["EvaluationCase"][];
            /** Dataset Version */
            dataset_version: string;
            /** Failed Cases */
            failed_cases: number;
            metrics: components["schemas"]["EvaluationMetrics"];
            /** Passed Cases */
            passed_cases: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PolicyDetail */
        PolicyDetail: {
            /** Document Id */
            document_id: string;
            /** Excerpt */
            excerpt: string;
            /** Source */
            source: string;
            /** Text */
            text: string;
            /** Title */
            title: string;
        };
        /** PolicySummary */
        PolicySummary: {
            /** Document Id */
            document_id: string;
            /** Excerpt */
            excerpt: string;
            /** Source */
            source: string;
            /** Title */
            title: string;
        };
        /** RuntimeLinks */
        RuntimeLinks: {
            /** About */
            about: string;
            /** Assistant */
            assistant: string;
            /** Evaluations */
            evaluations: string;
            /** Openapi */
            openapi: string;
            /** Policies */
            policies: string;
        };
        /** RuntimeMetadata */
        RuntimeMetadata: {
            /** Backend */
            backend: string;
            /** Capabilities */
            capabilities: string[];
            /** Document Count */
            document_count: number;
            /** Evaluation Count */
            evaluation_count: number;
            links: components["schemas"]["RuntimeLinks"];
            /** Name */
            name: string;
            /** Version */
            version: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ask_api_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_stream_api_ask_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_evaluation_api_evaluations_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationReport"];
                };
            };
        };
    };
    metadata_api_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeMetadata"];
                };
            };
        };
    };
    policy_catalog_api_policies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicySummary"][];
                };
            };
        };
    };
    policy_detail_api_policies__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
